### ISSUE TITLE
https://linksharing.samsungcloud.com/hzPeiyWQoMpl

### ISSUE THREAD

**Issue by Arcomyala** [tronprotocol/documentation#403]
https://linksharing.samsungcloud.com/hzPeiyWQoMpl

_Originally posted by @Vanina095 in https://github.com/tronprotocol/documentation/issues/399#issuecomment-912959000_

**Comment by boughanmiadel** [comment]
Bonjour j'ai demandé plusieurs fois mon désabonnement je ne souhaite plus recevoir vos offres d'abonnement merci.

 
 

Envoyé: mardi 5 octobre 2021 à 22:55
De: "Arcomyala" ***@***.***>
À: "tronprotocol/documentation" ***@***.***>
Cc: "Subscribed" ***@***.***>
Objet: [tronprotocol/documentation] https://linksharing.samsungcloud.com/hzPeiyWQoMpl (#403)


 

https://linksharing.samsungcloud.com/hzPeiyWQoMpl

Originally posted by @Vanina095 in #399 (comment)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
